import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "react-slick";

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    autoplay: true,
    autoplaySpeed: 2000,
    pauseOnHover: true,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.main_wrp}>
          <div className="container">
            <div className="row salign-items-center">
              <div className="col-12 col-md-7">
                <div className={styles.left_side}>
                  <div className={styles.bag1}>
                    <h2>
                      Private Limited (Pvt Ltd) Company{" "}
                      <span>Registration Online In India</span>
                    </h2>
                    <p>
                      No more delays or difficulties! Register your business
                      with India’s #1 provider of company incorporation
                      services. Get a 7 day{" "}
                      <b
                        className="fw-bold "
                        style={{
                          display: "inline-block",
                          alignItems: "start",
                          gap: "2px",
                        }}
                      >
                        {/* <b className="fw-bold " style={{display:"inline-flex",alignItems:"center",gap:"2px"}}> */}
                        <img
                          src="https://assets.vakilsearch.com/live-images/star_tick.svg"
                          alt=""
                        />{" "}
                        Guaranteed
                      </b>{" "}
                      document upload to the MCA or receive a full{" "}
                      <span className="d-block">
                        refund <a href="">T&C*</a>
                      </span>{" "}
                    </p>
                  </div>

                  <div className={styles.bag2}>
                    <img
                      src="https://assets.vakilsearch.com/live-images/youtube_play.svg"
                      alt=""
                    />
                    <a href="">Click to watch 60 seconds video</a>
                  </div>
                  <div className={styles.bag3}>
                    <p>
                      <b className="fw-bold">50,000+</b> businesses incorporated
                      since 2011
                    </p>
                  </div>

                  <div className={styles.slide_slder}>
                    <Slider {...settings}>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className={styles.slide_sec}>
                          <img
                            src="https://assets.vakilsearch.com/live-images/client-3.svg"
                            alt=""
                          />

                          <div>
                            <p>
                              Mr. Hrishikesh Datar, the founder of Vakilsearch,
                              encouraged and also provided me with a fast and
                              cost-effective Pvt Ltd registration, and I highly
                              recommend their services.
                            </p>

                            <h6>
                              <b className="fw-bold">Founder</b> - Chef & Chief
                              Baking officer of Four Seasons Pastry
                            </h6>
                          </div>
                        </div>
                      </div>
                    </Slider>
                  </div>
                </div>
              </div>
              <div className={"col-12 col-md-5" } id={styles.dsdede}>
                <div className={styles.form_sec}>
                <img src="https://assets.vakilsearch.com/live-images/diwalioffer.svg" className={styles.imgh} alt="" />
                  <form action="">
                    <h3>Register your company today</h3>
                    <div class="form-floating mb-3 mt-4">
                      <input
                        type="email"
                        class="form-control"
                        id="floatingInput"
                        placeholder="name@example.com"
                      />
                      <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-3">
                      <input
                        type="email"
                        class="form-control"
                        id="floatingInput"
                        placeholder="name@example.com"
                      />
                      <label for="floatingInput">Mobile Number</label>
                    </div>
                    <div class="form-floating mb-3">
                      <input
                        type="email"
                        class="form-control"
                        id="floatingInput"
                        placeholder="name@example.com"
                      />
                      <label for="floatingInput">City</label>
                    </div>

                    <div className={styles.lart_ftr}>
                     <p> Get easy updates through
                      {" "}
                      <img
                        src="https://assets.vakilsearch.com/live-images/account-bookkeeping/logos_whatsapp.svg"
                        alt=""
                      />
                      {" "}
                      Whatsapp</p>
                    </div>

                    <button>Talk to registration expert</button>
                  </form>
                </div>
              </div>
            </div>
            <div className={("row", styles.ftr_row)}>
              <div className="col-12">
                <div className={styles.ftr_para}>
                  <p>
                    Get Partner Benefits Worth Upto 4 lakhs by Incorporating
                    Your Company With Us!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* <div className="wrp_f">
        <div className="container">
        <div className="row">
            <div className="col-12">
                  <div className={styles.ftr_para}>
                    <p>Get Partner Benefits Worth Upto 4 lakhs by Incorporating Your Company With Us!</p>
                  </div>
              </div>
            </div>
        </div>
      </div> */}
    </>
  );
}
